# Generated by Django 3.2.8 on 2021-10-19 01:54

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('author', models.CharField(max_length=60)),
                ('postcaption', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('hashtag', models.ManyToManyField(to='cloneapp.HashTag')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloneapp.location')),
            ],
        ),
    ]
