# Generated by Django 3.2.8 on 2021-10-21 08:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cloneapp', '0003_comment_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postcaption',
            field=tinymce.models.HTMLField(),
        ),
    ]
